Repository MarkusPaulsen/TheSpoon, pull requests merged in 2019-12, with the labels that each got.

#122 Create README.md
  mobileApp/README.md
Labels: Mobile, Task

#131 Backend stub
  API_reference.yaml
  backendStub/api/swagger.yaml
  backendStub/controllers/Customer.js
  backendStub/controllers/Frikk.js
  backendStub/controllers/Matej.js
  backendStub/package-lock.json
  backendStub/service/CustomerService.js
  backendStub/service/FrikkService.js
  backendStub/service/MatejService.js
  package-lock.json
  package.json
Labels: Backend

#133 Updated models according to new DB-design
  models/itemReview.js
  models/menu.js
  models/menuItem.js
  models/menuReview.js
  routes/searchMenu.js
Labels: Backend

#134 Update API reference to version 5.1
  API_reference.yaml
Labels: Backend

#135 Update API reference to version 5.2
  API_reference.yaml
  backendStub/service/CustomerService.js
Labels: Backend

#136 Connection of review to endpoints
  mobileApp/components/review/components/continueButton.js
  mobileApp/components/review/views/reviewAddImage.js
  mobileApp/components/review/views/reviewAddItems.js
  mobileApp/components/review/views/reviewAddMenu.js
  mobileApp/components/review/views/reviewAddRestaurant.js
  mobileApp/components/review/views/reviewItems.js
  mobileApp/components/review/views/reviewOverall.js
Labels: Mobile

#137 Backend sprint5
  middleware/checkIfCustomerMiddleware.js
  models/menuReview.js
  models/taggedMenu.js
  package-lock.json
  router.js
  routes/createReview.js
  routes/manageCustomerInformation.js
  routes/manageCustomerReviews.js
  routes/manageMenuInformation.js
  routes/menuItem.js
  routes/searchByMenuItem.js
  routes/searchMenu.js
  thespoon/src/components/authentification/RegisterCustomer.js
  utils/credentialsAlreadyUsed.js
Labels: Backend

#139 Set travis to run tests
  .travis.yml
Labels: Testing

#140 Fix yml Travis file
  .travis.yml
Labels: Testing

#141 Backend stub
  API_reference.yaml
  backendStub/api/swagger.yaml
  backendStub/controllers/Emilio.js
  backendStub/controllers/Frikk.js
  backendStub/controllers/Marin.js
  backendStub/controllers/Owner.js
  backendStub/package-lock.json
  backendStub/service/EmilioService.js
  backendStub/service/FrikkService.js
  backendStub/service/MarinService.js
  backendStub/service/OwnerService.js
Labels: Backend

#142 Login/Logout and profile-page
  mobileApp/App.js
  mobileApp/components/login/login.js
  mobileApp/components/menupage/menupage.js
  mobileApp/components/profile/profile.js
  mobileApp/components/review/review.js
  mobileApp/components/review/views/reviewAddImage.js
  mobileApp/components/review/views/reviewAddItems.js
  mobileApp/components/review/views/reviewAddMenu.js
  mobileApp/components/review/views/reviewAddRestaurant.js
  mobileApp/components/search/search.js
  mobileApp/styles/typography.js
  mobileApp/yarn.lock
Labels: Mobile

#143 Update API reference to version 6.1
  API_reference.yaml
  routes/manageMenuInformation.js
Labels: Backend

#144 enable uploading .jpg images
  utils/image-upload.js
Labels: Backend

#145 Backend stub
  API_reference.yaml
  backendStub/api/swagger.yaml
  backendStub/controllers/Customer.js
  backendStub/controllers/Owner.js
  backendStub/package-lock.json
  backendStub/service/CustomerService.js
  backendStub/service/FrikkService.js
  backendStub/service/OwnerService.js
Labels: Backend

#147 Fix bug in backend stub
  API_reference.yaml
  backendStub/api/swagger.yaml
Labels: Backend

#150 Mobile/sorting
  mobileApp/components/menupage/menupage.js
  mobileApp/components/search/search.js
Labels: Mobile

#151 Mobile/delete review
  mobileApp/components/profile/profile.js
Labels: Mobile

#153 Backend sprint6 1
  jest.config.js
  jest.setup.js
  models/customer.js
  models/menu.js
  router.js
  routes/createReview.js
  routes/getTags.js
  routes/manageCustomerReviews.js
  routes/manageMenuInformation.js
  routes/manageRestaurantInformation.js
  routes/pendingReviews.js
  routes/searchByMenuItem.js
  routes/searchMenu.js
  tests/integration/routes/getTags.test.js
  tests/integration/routes/login.test.js
Labels: Backend

#154 Update API reference and backend stub to version 6.4
  API_reference.yaml
  backendStub/api/swagger.yaml
  backendStub/controllers/Emilio.js
  backendStub/controllers/Frikk.js
  backendStub/controllers/Marin.js
  backendStub/service/CustomerService.js
  backendStub/service/EmilioService.js
  backendStub/service/FrikkService.js
  backendStub/service/MarinService.js
Labels: Backend

#158 Fix mistake
  models/menuItem.js
  package-lock.json
  routes/manageCustomerReviews.js
Labels: Backend

#157 Fix bcrypt version
  package-lock.json
  package.json
Labels: Backend

#159 Update API reference to version 7.0
  API_reference.yaml
  middleware/authorizationMiddleware.js
  middleware/checkIfCustomerMiddleware.js
  middleware/checkIfOwnerMiddleware.js
  middleware/findRestaurantOfOwnerMiddleware.js
  middleware/inputValidationMiddleware.js
  routes/createReview.js
  routes/image-upload.js
  routes/manageCustomerReviews.js
  routes/manageMenuInformation.js
  routes/menuItem.js
  routes/pendingReviews.js
Labels: Backend

#148 Mobile/review,Login, Logout, Profile
  mobileApp/App.js
  mobileApp/assets/addImage.png
  mobileApp/assets/fonts/Roboto-Bold.ttf
  mobileApp/assets/fonts/Roboto-Medium.ttf
  mobileApp/assets/navigationMenu/addReview.png
  mobileApp/assets/navigationMenu/profile.png
  mobileApp/assets/navigationMenu/search.png
  mobileApp/components/login/login.js
  mobileApp/components/menupage/ItemReview.js
  mobileApp/components/menupage/menupage.js
  mobileApp/components/profile/profile.js
  mobileApp/components/review/components/backButton.js
  mobileApp/components/review/components/circles.js
  mobileApp/components/review/components/continueButton.js
  mobileApp/components/review/review.js
  mobileApp/components/review/views/reviewAddImage.js
  mobileApp/components/review/views/reviewAddItems.js
  mobileApp/components/review/views/reviewAddMenu.js
  mobileApp/components/review/views/reviewAddRestaurant.js
  mobileApp/components/review/views/reviewItems.js
  mobileApp/components/review/views/reviewOverall.js
  mobileApp/components/search/search.js
  mobileApp/package-lock.json
  mobileApp/package.json
  mobileApp/services/api.js
  mobileApp/styles/colors.js
  mobileApp/styles/fontstyles.js
  mobileApp/styles/typography.js
  mobileApp/yarn.lock
  utils/image-upload.js
Labels: Mobile

#161 Backend sprint7
  jest.setup.js
  middleware/updateRatingMiddleware.js
  routes/createReview.js
  routes/image-upload.js
  routes/manageCustomerInformation.js
  routes/manageCustomerReviews.js
  routes/manageMenuInformation.js
  routes/manageRestaurantInformation.js
  routes/menuItem.js
  routes/pendingReviews.js
  routes/searchByMenuItem.js
  routes/searchMenu.js
  tests/integration/routes/createReview.test.js
  tests/integration/routes/getTags.test.js
  tests/integration/routes/login.test.js
  validationSchemas.js
Labels: Backend

#166 Mobile/betafixes
  mobileApp/App.js
  mobileApp/assets/login-email.png
  mobileApp/assets/login-password.png
  mobileApp/components/login/login.js
  mobileApp/components/menupage/ItemReview.js
  mobileApp/components/menupage/menupage.js
  mobileApp/components/profile/profile.js
  mobileApp/components/review/views/reviewAddImage.js
  mobileApp/components/review/views/reviewItems.js
  mobileApp/components/search/search.js
Labels: Bug, Mobile

#165 Testing the mobileApp
  .travis.yml
  mobileApp/App.js
  mobileApp/App.test.js
  mobileApp/components/CustomizedButton.js
  mobileApp/components/CustomizedButton.test.js
  mobileApp/components/Loading.js
  mobileApp/components/Loading.test.js
  mobileApp/components/home/homescreen.js
  mobileApp/components/landingpage/landingpage.js
  mobileApp/components/login/LoginScreen.js
  mobileApp/components/login/LoginScreen.test.js
  mobileApp/components/login/validation.test.js
  mobileApp/components/menupage/ItemReview.js
  mobileApp/components/menupage/ItemReview.test.js
  mobileApp/components/menupage/Menu.js
  mobileApp/components/menupage/Menu.test.js
  mobileApp/components/profile/Profile.js
  mobileApp/components/profile/Profile.test.js
  mobileApp/components/review/review.js
  mobileApp/components/review/views/ReviewAddImage.js
  mobileApp/components/review/views/ReviewAddImage.test.js
  mobileApp/components/review/views/ReviewAddItems.js
  mobileApp/components/review/views/ReviewAddItems.test.js
  mobileApp/components/review/views/ReviewAddMenu.js
  mobileApp/components/review/views/ReviewAddMenu.test.js
  mobileApp/components/review/views/ReviewAddRestaurant.js
  mobileApp/components/review/views/ReviewAddRestaurant.test.js
  mobileApp/components/review/views/ReviewItems.js
  mobileApp/components/review/views/ReviewItems.test.js
  mobileApp/components/review/views/ReviewOverall.js
  mobileApp/components/review/views/ReviewOverall.test.js
  mobileApp/components/search/Search.js
  mobileApp/components/search/Search.test.js
  mobileApp/i18n.js
  mobileApp/package-lock.json
  mobileApp/package.json
  mobileApp/services/api.test.js
  mobileApp/setupTests.js
  mobileApp/yarn.lock
  package-lock.json
Labels: Mobile, Testing

#169 Update API reference to version 7.1
  API_reference.yaml
Labels: Backend

#171 Set up clustering
  ecosystem.config.js
  package-lock.json
  package.json
Labels: Backend

#172 Clustering
  Procfile
  package.json
Labels: Backend

#170 Update API reference to version 7.2
  API_reference.yaml
Labels: Backend
