Repository MarkusPaulsen/TheSpoon, pull requests merged in 2020-01, with the labels that each got.

#176 Backend sprint7
  middleware/updateRatingMiddleware.js
  models/customer.js
  models/openingHours.js
  models/restaurants.js
  routes/consultantStatistics.js
  routes/createReview.js
  routes/manageRestaurantInformation.js
  routes/menuItem.js
  routes/pendingReviews.js
  routes/searchMenu.js
Labels: Backend

#177 Search MenuItem now case insensitive, small fix in response message
  routes/searchByMenuItem.js
  routes/searchMenu.js
Labels: Backend

#181 Mobile/show opening hours
  mobileApp/components/menupage/Menu.js
  mobileApp/components/menupage/OpeningHours.js
  mobileApp/components/review/views/ReviewItems.js
  mobileApp/components/review/views/ReviewItems.test.js
  mobileApp/package-lock.json
  mobileApp/package.json
  package-lock.json
Labels: Mobile

#186 Mobile/bugfix
  mobileApp/components/review/views/ReviewAddItems.js
  mobileApp/components/review/views/ReviewAddMenu.js
  mobileApp/components/review/views/ReviewAddRestaurant.js
  mobileApp/components/review/views/ReviewItems.js
  mobileApp/components/review/views/ReviewOverall.js
  mobileApp/components/search/Search.js
Labels: Bug, Mobile

#185 Update API reference to version 8.1
  API_reference.yaml
  middleware/authorizationMiddleware.js
Labels: Backend

#188 Backend sprint7
  middleware/updateRatingMiddleware.js
  models/itemReview.js
  routes/createReview.js
  routes/getTags.js
  routes/manageCustomerInformation.js
  routes/manageCustomerReviews.js
  routes/manageMenuInformation.js
  routes/manageRestaurantInformation.js
  routes/ownerProfile.js
  routes/pendingReviews.js
  routes/searchByMenuItem.js
  tests/integration/routes/consultantLogin.test.js
  tests/integration/routes/manageCustomerInformation.test.js
  validationSchemas.js
Labels: Backend

#189 small fix in changeing customer profile
  routes/manageCustomerInformation.js
Labels: Backend

#190 fix in getting customer information
  routes/manageCustomerInformation.js
Labels: Backend

#193 Update README.md
  README.md
Labels: Backend

#196 Update API reference to version 8.2
  API_reference.yaml
Labels: Backend

#198 Backend sprint7
  routes/ownerProfile.js
  routes/searchMenu.js
  tests/integration/routes/consultantStatistics.test.js
  tests/integration/routes/manageCustomerInformation.test.js
  tests/integration/routes/manageCustomerReviews.test.js
  tests/integration/routes/menuItem.test.js
  tests/integration/routes/ownerProfile.test.js
  tests/integration/routes/registrationCustomer.test.js
  tests/integration/routes/registrationOwner.test.js
  tests/integration/routes/searchByMenuItem.test.js
  tests/integration/routes/searchMenu.test.js
Labels: Backend

#201 Backend sprint7
  package.json
  tests/integration/routes/consultantLogin.test.js
  tests/integration/routes/consultantStatistics.test.js
  tests/integration/routes/createReview.test.js
  tests/integration/routes/getTags.test.js
  tests/integration/routes/login.test.js
  tests/integration/routes/manageCustomerInformation.test.js
  tests/integration/routes/manageCustomerReviews.test.js
  tests/integration/routes/manageMenuInformation.test.js
  tests/integration/routes/manageRestaurantInformation.test.js
  tests/integration/routes/menuItem.test.js
  tests/integration/routes/ownerProfile.test.js
  tests/integration/routes/registrationConsultant.test.js
  tests/integration/routes/registrationCustomer.test.js
  tests/integration/routes/registrationOwner.test.js
  tests/integration/routes/searchByMenuItem.test.js
  tests/integration/routes/searchMenu.test.js
Labels: Backend

#202 Delete TagItem.js
  thespoon/src/components/restaurantPage/Items/TagItem.js
Labels: Web

#203 tag design update
  thespoon/src/components/RestaurantPage/Items/Menu.js
  thespoon/src/components/RestaurantPage/Items/MenuItem.js
  thespoon/src/components/RestaurantPage/Items/TagItem.js
  thespoon/src/components/RestaurantPage/Modals/AddMenuItemModal.js
  thespoon/src/components/RestaurantPage/Modals/EditMenuItemModal.js
  thespoon/src/index.scss
Labels: Web

#204 Add unit testing for validation schemas
  tests/unit/validationSchemas.test.js
Labels: Backend

#208 Update backend stub to version 8.2
  backendStub/.swagger-codegen/VERSION
  backendStub/api/swagger.yaml
  backendStub/controllers/Customer.js
  backendStub/controllers/Emilio.js
  backendStub/controllers/Frikk.js
  backendStub/controllers/Marin.js
  backendStub/controllers/Owner.js
  backendStub/package-lock.json
  backendStub/service/CustomerService.js
  backendStub/service/EmilioService.js
  backendStub/service/FrikkService.js
  backendStub/service/GenericUserService.js
  backendStub/service/MarinService.js
  backendStub/service/MatejService.js
  backendStub/service/OwnerService.js
Labels: Backend

#210 Web/consultant pages
  thespoon/src/App.js
  thespoon/src/assets/canvas/canvasjs.min.js
  thespoon/src/assets/canvas/canvasjs.react.js
  thespoon/src/components/ConsultantPage/ConsultantLoginModal.js
  thespoon/src/components/ConsultantPage/ConsultantPage.js
  thespoon/src/components/ConsultantPage/ConsultantRegisterModal.js
  thespoon/src/components/ConsultantPage/Modals/ChooseConsultantModal.js
  thespoon/src/components/ConsultantPage/Nationality.js
  thespoon/src/components/ConsultantPage/Pie.js
  thespoon/src/components/HomePage/HomePage.js
  thespoon/src/components/HomePage/Modals/LogOutModal.js
  thespoon/src/components/Layout/ConsultantHeader.js
  thespoon/src/components/Layout/ConsultantLayout.js
  thespoon/src/components/restaurantPage/Items/TagItem.js
  thespoon/src/constants/Modals.js
  thespoon/src/constants/Paths.js
  thespoon/src/containers/CustomModal.js
  thespoon/src/index.scss
  thespoon/src/validation/validators.js
Labels: Web

#211 Deleted Your menu has pending reviews...
  package-lock.json
  thespoon/package-lock.json
  thespoon/src/components/RestaurantPage/YourRestaurantPage.js
Labels: Web

#214 Latest release
  thespoon/public/index.html
  thespoon/src/components/RestaurantPage/Items/MenuItem.js
  thespoon/src/index.scss
Labels: Backend, Design, Mobile, Web

#215 Make the database url an environment variable
  config/custom-environment-variables.json
  config/default.json
  jest.setup.js
  thespoon/src/constants/Timeouts.js
  utils/environmentVariablesCheck.js
Labels: Backend, Web

#216 Fix typos in backend tests
  tests/integration/routes/registrationConsultant.test.js
  tests/integration/routes/registrationOwner.test.js
Labels: Backend

#217 Web/tests
  config/default.json
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/ConsultantLoginTesting.js
  cypress/integration/ConsultantRegistrationTesting.js
  cypress/integration/CustomerRegistrationTesting.js
  cypress/integration/EditRestauranOwnerProfiletTesting.js
  cypress/integration/EditRestaurantTesting.js
  cypress/integration/LoginTesting.js
  cypress/integration/RegistrationTesting.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Web

#218 Final merge in master
  config/custom-environment-variables.json
  config/default.json
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/ConsultantLoginTesting.js
  cypress/integration/ConsultantRegistrationTesting.js
  cypress/integration/CustomerRegistrationTesting.js
  cypress/integration/EditRestauranOwnerProfiletTesting.js
  cypress/integration/EditRestaurantTesting.js
  cypress/integration/LoginTesting.js
  cypress/integration/RegistrationTesting.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.setup.js
  package-lock.json
  package.json
  tests/integration/routes/registrationConsultant.test.js
  tests/integration/routes/registrationOwner.test.js
  thespoon/src/constants/Timeouts.js
  utils/environmentVariablesCheck.js
Labels: Backend, General, Mobile, Web
